language: node_js
node_js:
- '12.6.0'
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/z-games-lost-cities
    branch: master
  skip_cleanup: true
  api_key:
    secure: AolI2/RW4qCjoCs+9hvtunpuP4nWVE42nQUN9IGwUrNrYQkEeKPRSbvh2e0QgfQIuNCa4XfnX4kqCkpOI3nJ5h/uRKxE7fFrYphJycSPS6bhrWa9GL/A/VdfEad7+0XCLoePcDyifOQgJFIRZ8x3hm+ep0S83fA7Hr9TMWUNiFeCqujAaLySxc/XKcM9FE7uAoM9ZYLzsZhGM74gA/awncEmw+igL2Qjj5veQmNouX+HBs+NIVu/LnmwXMjUDPQaN2aX3fmDdkAKfErtKY6KBwemiwrr6CDikwV9z22br2H51BFcqGLGQKS0ZTsPAToy25QnRTCnKbf6MQAePCIQRMzhpiYbhg5sWcblf8V/XjyfbDAUGwBpfSRGIRYT2qUNCh91kWSOLXcrLFWV6lOkcwvJgPUCmto2J/RvRM7DdafB1HwnGR9xAQv2WgufZqVk0TdvIq41CRYVXVXvW7hUM3a8m3n5mN1vu5IoUqKD0GbPqOI2G7LxpRin0kvKookyOVtu5I9XLCsDZt5TNC8d2RjWy5Mmlwd+MQmcGNXI4Q3kPdsVUV+lfqC2kFLaACmnz9i8giBLnqTS0qIjGSZC5n/z5Fchd3Y387geZFtLo/7GVcA62REh1KREoUyFFfQ0vmjKWiZWcsQV1Ip+OBx2hnGJFdT89RKGptAsUUwbXiU=
